name: Print Hayat Hello File

on:
  push:
    branches:
      - main

jobs:
  read-hello-file-hayat:
    runs-on: ubuntu-latest
#  checkout the repository's code
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

# tep to read the hello.txt file and print its content to the workflow's log.
      - name: Read hello.txt
        run: |
          echo "Read and Output"
          cat hello.txt
