name: Print Hello File

on:
  push:
    branches:
      - main

jobs:
  read-hello:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Read and print hello.txt
      - name: Read hello.txt
        run: |
          echo "Contents of hello.txt:"
          cat hello.txt
